### ISSUE TITLE
Roles not iterable error

### ISSUE THREAD

**Issue by Hosfad** [OutwalkStudios/discord-backup#1]
Hey there im using your package and im getting a roles not iterable error when trying to load a backup . Any help please ? 
it happens right after request 2 log 
Here is the stack trace
```
TypeError: e.roles is not iterable
    at Object.<anonymous> (/home/hosfad/Desktop/discord-backup-api/node_modules/@outwalk/discord-backup/dist/index.js:1:8952)
    at Generator.next (<anonymous>)
    at /home/hosfad/Desktop/discord-backup-api/node_modules/@outwalk/discord-backup/dist/index.js:1:8091
    at new Promise (<anonymous>)
    at N (/home/hosfad/Desktop/discord-backup-api/node_modules/@outwalk/discord-backup/dist/index.js:1:7911)
    at Object.H [as loadRoles] (/home/hosfad/Desktop/discord-backup-api/node_modules/@outwalk/discord-backup/dist/index.js:1:8902)
    at Object.<anonymous> (/home/hosfad/Desktop/discord-backup-api/node_modules/@outwalk/discord-backup/dist/index.js:1:15482)
    at Generator.next (<anonymous>)
    at i (/home/hosfad/Desktop/discord-backup-api/node_modules/@outwalk/discord-backup/dist/index.js:1:12126)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[ERROR] 04:05:40 TypeError: e.roles is not iterable
```

**Comment by jleeson** [comment]
Hey @Hosfad, thanks for creating this issue, I will look into it and let you know what I find, If its a bug in the package ill make sure I get it fixed as soon as possible.

**Comment by jleeson** [comment]
Hey @Hosfad, i did some testing and did not run into this issue on the latest version, try updating to v0.3.0 and give it a try. The latest version also resolves several other problems.

**Comment by jleeson** [comment]
closing due to inactivity. If this is still a problem you are having I can reopen.
