### ISSUE TITLE
RangeError [BitFieldInvalid]: Invalid bitfield flag or number: [object Object].

### ISSUE THREAD

**Issue by norzlevrai** [OutwalkStudios/discord-backup#27]
RangeError [BitFieldInvalid]: Invalid bitfield flag or number: [object Object].
    at IntentsBitField.resolve (C:\Users\levra\node_modules\discord.js\src\util\BitField.js:174:11)
    at new BitField (C:\Users\levra\node_modules\discord.js\src\util\BitField.js:33:38)
    at new IntentsBitField (C:\Users\levra\node_modules\discord.js\src\util\IntentsBitField.js:9:1)
    at Object.create (C:\Users\levra\node_modules\@outwalk\discord-backup\dist\index.cjs:664:19)
    at Object.run (C:\Users\levra\Desktop\Tijuana Gestion\src\commands\slash\Gestion\backup.js:57:34)
    at Object.run (C:\Users\levra\Desktop\Tijuana Gestion\src\events\GuildInteractions\interactionCreate.js:159:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'BitFieldInvalid'
}

**Comment by jleeson** [comment]
@norzlevrai can you provide more information about whats causing this error or some code to reproduce it?

**Comment by norzlevrai** [comment]
When i execute /backup create i have this error: RangeError [BitFieldInvalid]: Invalid bitfield flag or number: [object Object].

Thats my code.
```js
const { SlashCommandBuilder, ChatInputCommandInteraction, EmbedBuilder } = require('discord.js');
const ExtendedClient = require('../../../class/ExtendedClient');

module.exports = {
    
    structure: new SlashCommandBuilder()
        .setName('backup')
        .setDescription('Allows you to manage server backups.')
        .addSubcommand(subcommand =>
            subcommand
                .setName('create')
                .setDescription('Creates a server backup.')
        )
        .addSubcommand(subcommand =>
            subcommand
                .setName('list')
                .setDescription('Displays the list of all backups.')
        )
        .addSubcommand(subcommand =>
            subcommand
                .setName('load')
                .setDescription('Loads a backup.')
                .addStringOption(option =>
                    option.setName('id')
                        .setDescription('ID of the backup to load')
                        .setRequired(true)
                )
        )
        .addSubcommand(subcommand =>
            subcommand
                .setName('delete')
                .setDescription('Deletes a backup.')
                .addStringOption(option =>
                    option.setName('id')
                        .setDescription('ID of the backup to delete')
                        .setRequired(true)
                )
        ),
    options: {
        cooldown: 5000,
        category: '⚔️ Management'
    },
    /**
     * @param {ExtendedClient} client 
     * @param {ChatInputCommandInteraction} interaction 
     */
    
    run: async (client, interaction) => {
        const backup = require("@outwalk/discord-backup");
        const subcommand = interaction.options.getSubcommand();

        switch (subcommand) {
            case 'create':
                await backup.create(interaction.guild, {
                    maxMessagesPerChannel: 100,
                    jsonBeautify: true
                })
                .then((backupData) => {
                    interaction.reply(`Backup successfully created. Use \`/backup load ${backupData.id}\` to load the backup.`);
                }).catch(err => {
                    console.error(err);
                    interaction.reply(`An error occurred while creating the backup.`);
                });
                break;

            case 'list':
                try {
                    const backupsList = backup.list(); // Get the list of backups
                    let descriptionText = '';

                    if (backupsList.length === 0) {
                        // If the list is empty, display an appropriate message
                        descriptionText = "No backups found.";
                    } else {
                        // Otherwise, concatenate the backup IDs with line breaks
                        descriptionText = backupsList.join('\n');
                    }

                    const listEmbed = new EmbedBuilder()
                        .setAuthor({ name: '📰 List of Backups' }) // Use an object to set the author
                        .setDescription(`\`\`\`${descriptionText}\`\`\``) // Use the constructed description text
                        .setColor(client.color);

                    interaction.reply({ embeds: [listEmbed] });
                } catch (err) {
                    console.error(err);
                    interaction.reply(`An error occurred while retrieving the backups.`);
                }
                break;

            case 'load':
                const backupIDToLoad = interaction.options.getString('id');
                backup.fetch(backupIDToLoad).then(async () => {
                    interaction.reply(`When the backup is loaded, all channels, roles, etc. will be replaced!`);
                    try {
                        await backup.load(backupIDToLoad, interaction.guild);
                        interaction.user.send(`The backup was successfully loaded.`);
                    } catch (err) {
                        console.error(err);
                        interaction.user.send(`Sorry, an error occurred. Please check if I have administrator permissions.`);
                    }
                }).catch(err => {
                    console.error(err);
                    interaction.reply(`No backup found with ID \`${backupIDToLoad}\``);
                });
                break;

            case 'delete':
                const backupIDToDelete = interaction.options.getString('id');
                backup.remove(backupIDToDelete).then(() => {
                    interaction.reply(`Backup ${backupIDToDelete} was successfully deleted.`);
                }).catch(err => {
                    console.error(err);
                    interaction.reply(`An error occurred while deleting the backup.`);
                });
                break;

            default:
                interaction.reply('Unrecognized command.');
                break;
        }
    }
};
```

**Comment by norzlevrai** [comment]
discord.js : 14.15.1
    Node.js : v20.13.1

**Comment by norzlevrai** [comment]
I found the problem, The package was not added to the package.json, so I ran ```npm i @outwalk/discord-backup -s```. Sorry for the inconvenience.

**Comment by jleeson** [comment]
Glad you got it working!
