### ISSUE TITLE
Backup Load Issue

### ISSUE THREAD

**Issue by SjogrenDev** [OutwalkStudios/discord-backup#36]
It seems like that loading a backup with saved members causes issues when the member already has the role.

`DiscordAPIError[50035]: Invalid Form Body
roles[4][SET_TYPE_ALREADY_CONTAINS_VALUE]: The set already contains this value
roles[6][SET_TYPE_ALREADY_CONTAINS_VALUE]: The set already contains this value
    at handleErrors (/home/container/node_modules/@discordjs/rest/dist/index.js:730:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:1133:23)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/index.js:963:14)
    at async _REST.request (/home/container/node_modules/@discordjs/rest/dist/index.js:1278:22)
    at async GuildMemberManager.edit (/home/container/node_modules/discord.js/src/managers/GuildMemberManager.js:381:15)`

**Comment by jleeson** [comment]
This should be fixed in v0.7.7.
